#!/usr/bin/env bash



##
# Capture and display output simulataneously.
__capture() { tee captured.log }



## Toggle spotlight indexing.
__toggle_spotlight() {
  mdutil -as | grep --quiet "enabled"; SPOTLIGHT_ENABLED="$?"
  [ "$SPOTLIGHT_ENABLED" -eq 0 ] && sudo mdutil -a -i off || sudo mdutil -a -i on
}
