#!/usr/bin/env bash

# count displays
__count_displays() {
  /usr/sbin/system_profiler SPDisplaysDataType | grep -Ew 'Resolution' -c
}

# get unique file extensions for a directory
__file_extensions() {
  find "$1" -depth 0 -type f | sed -En 's|.*/[^/]+\.([^/.]+)$|\1|p' | sort -u
}

# clean up computer
__clean() {
  CLEAN=("$HOME/Desktop" "$HOME/Downloads")

  for dir in "${CLEAN[@]}"; do
    for ext in $(__file_extensions $dir); do
      mkdir -p "$HOME/$ext"
      mv $dir/*.$ext $HOME/$ext
    done
  done
}

__top_processes_by_cpu_utilization() {
  command ps -cu "$USER" -r -o command,%cpu,%mem | command head -n "${1:-10}"
}

# watch a directory and perform an action on the changed file
__watch() {
  fswatch -0 "$1" | while read -d "" event; do "$2" ${event}; done
}


