#!/usr/bin/env bash



## Edit a remote file locally with Vim.
rvim () {
  REMOTE="$1"; FILEPATH="$2"
  [ -n "$REMOTE" ] && [ -n "$FILEPATH" ] || { echo "ERROR: missing one or more required arguments"; exit; }
  vim scp://"$1"/"$2"
}
