#!/usr/bin/env bash

# run vagrant commands from anywhere
vagabond () {
  [ "$#" -lt 2 ] && echo "usage: vagabond PROJECT CMD" && return

  MAX_RECURSION_DEPTH=4

  TOP_LEVEL="$HOME"
  VAGRANT_FILE="*/$1/Vagrantfile"
  VAGRANT_CMD=("${@:2}")

  find $TOP_LEVEL -type f \
                  -path $VAGRANT_FILE \
                  -maxdepth $MAX_RECURSION_DEPTH \
                  -execdir command vagrant $VAGRANT_CMD \;
}

# make the common environments autocomplete-able
complete -W "developer-setup devbox" vagabond

