#!/usr/bin/env bash

__docker_registry() {
  docker run -d -p 5000:5000 --restart=always --name=registry registry:2
}

__docker_clean() {
  docker system prune --all --filter "until=336h"
}

# launch a jenkins container
__jenkins() {
  CODE=/Users/vmargiotta/Documents/iseatz
  docker run -u root \
             --rm \
             -d \
             -p 8080:8080 \
             -p 50000:50000 \
             -v $CODE:/var/jenkins_home/code \
             -v jenkins-data:/var/jenkins_home \
             -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean
}

# monitor docker containers
__monitor_docker() {
  while true; do docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Command}}\t{{.Networks}}\t{{.Ports}}\t{{.Status}}"; sleep 5; clear; done
}

# docker managements
__remove_all_containers() {
  command docker rm -vf $(command docker ps -aq)
}

__remove_all_images() {
  command docker rmi -f $(command docker images -aq)
}

