#!/usr/bin/env zsh

export ZSH=$HOME/.oh-my-zsh
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
export PATH="$PATH:/opt/homebrew/bin"
export EDITOR=vim

ZSH_THEME=personal

plugins=(
  asdf
  bgnotify
  brew
  catimg
  docker
  vi-mode
  vundle
  zsh-autosuggestions
)

##
# Push a directory onto the stack whenever `cd` is used,
# being silent about it and ensuring that the contents of the stack is a set.
setopt AUTO_PUSHD
setopt PUSHD_SILENT
setopt PUSHD_IGNORE_DUPS

##
# Enable bash completion
# TODO: Is this still necessary?
autoload bashcompinit && bashcompinit

source $HOME/.aliases
source $HOME/.functions
source $ZSH/oh-my-zsh.sh

# Source a few special aliases if they exist
[ -f "$HOME/.config/iseatz/aliases" ] && source "$HOME/.config/iseatz/aliases"
[ -f "$HOME/.config/cyberpolitik.com/aliases" ] && source "$HOME/.config/cyberpolitik.com/aliases"

source $(brew --prefix asdf)/asdf.sh
eval "$(/opt/homebrew/bin/brew shellenv)"
